---
name: Bug Report
description:: Create a bug report to help us improve ServerAssistantAI.
title: "[BUG] "
labels: ["Bug: Reported"]
assignees: 'BlueTree242'

---
Thank you for creating a bug report. Before you fill this out, please read the following:
1. Ensure you are running the latest version of ServerAssistantAI.
2. Check if the issue has already been reported. If it has, please comment with additional information on the existing issue instead of creating a new one.
3. Only report one bug per issue. This helps us keep track of individual problems more effectively.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. '...'
2. '....'
3. '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots & Videos**
If applicable, add screenshots or videos to help explain your problem.

**Server Information:**
- Minecraft Version: [e.g., 1.20.4]
- Server Software: [e.g., Paper, Spigot, Purpur]

**ServerAssistantAI Information:**
- ServerAssistantAI Version: [e.g., 1.2.13]
- DiscordSRV Version: [e.g., 1.27.0]
- DiscordSRVUtils Version: [e.g., 1.0.0]

**Other Plugins:**
- List any other relevant plugins that may interact with ServerAssistantAI

**Checklist:**
- [ ] The issue occurs on the latest version of ServerAssistantAI.
- [ ] The issue occurs without other plugins (except for required dependencies).
- [ ] I am using a supported Minecraft server software (Spigot, Paper, Purpur, etc.) and the issue still occurs.

**Server Log**
Please provide a link to your server's `latest.log` file, uploaded to a service like https://mcpaste.io/. Make sure to reproduce the issue right before uploading the log.

**Additional Context**
Add any other context about the problem here, such as:
- 'Specific AI models or services being used and relevant configuration settings'
